language: node_js
node_js:
  - '8'
script:
  - npm run build
before_deploy:
  - rm -rf dist/*
deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
